name: Check Them Vim Files
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    name: Linting

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1

      - uses: BSFishy/pip-action@v1
        with:
          packages: vim-vint

      - run: vint --verbose --stat $(find . -type f -name '*.vim')
